[tool.poetry]
name = "repl_python3_cocanbTranslator"
version = "0.1.0"
description = ""
authors = ["WoojinSon1 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
unidecode = "^1.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
